[theme]
base = "light"
primaryColor = "#1B4F72"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#EAECEE"
textColor = "#212529"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false